project 'SignalR.Client.ObjC Example.xcodeproj'
workspace '../SignalR.Client.ObjC'

target "OS X Example" do
    use_frameworks!
    platform :osx, '10.9'

    pod 'SignalR-ObjC', :path => '..'
end

target "iOS Example" do
    use_frameworks!
    platform :ios, '9.0'
    
    pod 'SignalR-ObjC', :path => '..'
end